"""
Instrument Definitions — Live Tokens from Kotak Neo Scrip Master

Auto-generated from scrip master on 2026-02-21.
Total: 178 instruments (175 stocks + 3 indexes).
"""

from dataclasses import dataclass
from typing import List


@dataclass(frozen=True)
class Instrument:
    """Immutable instrument definition."""
    symbol: str
    token: str
    segment: str


INSTRUMENTS: List[Instrument] = [
    # --- Indexes ---
    Instrument(symbol="NIFTY", token="26000", segment="nse_cm"),
    Instrument(symbol="BANKNIFTY", token="26009", segment="nse_cm"),
    Instrument(symbol="FINNIFTY", token="26037", segment="nse_cm"),

    # --- Stocks (alphabetical) ---
    Instrument(symbol="ABBOTINDIA", token="17903", segment="nse_cm"),
    Instrument(symbol="ABCAPITAL", token="21614", segment="nse_cm"),
    Instrument(symbol="ABFRL", token="30108", segment="nse_cm"),
    Instrument(symbol="ACC", token="22", segment="nse_cm"),
    Instrument(symbol="ADANIENT", token="25", segment="nse_cm"),
    Instrument(symbol="ADANIPORTS", token="15083", segment="nse_cm"),
    Instrument(symbol="ALKEM", token="11703", segment="nse_cm"),
    Instrument(symbol="AMBUJACEM", token="1270", segment="nse_cm"),
    Instrument(symbol="APOLLOHOSP", token="157", segment="nse_cm"),
    Instrument(symbol="ASIANPAINT", token="236", segment="nse_cm"),
    Instrument(symbol="ASTRAZEN", token="5610", segment="nse_cm"),
    Instrument(symbol="ATUL", token="263", segment="nse_cm"),
    Instrument(symbol="AUBANK", token="21238", segment="nse_cm"),
    Instrument(symbol="AUROPHARMA", token="275", segment="nse_cm"),
    Instrument(symbol="AXISBANK", token="5900", segment="nse_cm"),
    Instrument(symbol="BAJAJ-AUTO", token="16669", segment="nse_cm"),
    Instrument(symbol="BAJAJFINSV", token="16675", segment="nse_cm"),
    Instrument(symbol="BAJFINANCE", token="317", segment="nse_cm"),
    Instrument(symbol="BALRAMCHIN", token="341", segment="nse_cm"),
    Instrument(symbol="BANDHANBNK", token="2263", segment="nse_cm"),
    Instrument(symbol="BANKBARODA", token="4668", segment="nse_cm"),
    Instrument(symbol="BATAINDIA", token="371", segment="nse_cm"),
    Instrument(symbol="BEL", token="383", segment="nse_cm"),
    Instrument(symbol="BERGEPAINT", token="404", segment="nse_cm"),
    Instrument(symbol="BHARTIARTL", token="10604", segment="nse_cm"),
    Instrument(symbol="BHEL", token="438", segment="nse_cm"),
    Instrument(symbol="BIOCON", token="11373", segment="nse_cm"),
    Instrument(symbol="BOSCHLTD", token="2181", segment="nse_cm"),
    Instrument(symbol="BPCL", token="526", segment="nse_cm"),
    Instrument(symbol="BRITANNIA", token="547", segment="nse_cm"),
    Instrument(symbol="CANBK", token="10794", segment="nse_cm"),
    Instrument(symbol="CANFINHOME", token="583", segment="nse_cm"),
    Instrument(symbol="CHAMBLFERT", token="637", segment="nse_cm"),
    Instrument(symbol="CHOLAFIN", token="685", segment="nse_cm"),
    Instrument(symbol="CIPLA", token="694", segment="nse_cm"),
    Instrument(symbol="COALINDIA", token="20374", segment="nse_cm"),
    Instrument(symbol="COFORGE", token="11543", segment="nse_cm"),
    Instrument(symbol="COLPAL", token="15141", segment="nse_cm"),
    Instrument(symbol="CONCOR", token="4749", segment="nse_cm"),
    Instrument(symbol="COROMANDEL", token="739", segment="nse_cm"),
    Instrument(symbol="CROMPTON", token="17094", segment="nse_cm"),
    Instrument(symbol="CUB", token="5701", segment="nse_cm"),
    Instrument(symbol="CUMMINSIND", token="1901", segment="nse_cm"),
    Instrument(symbol="DABUR", token="772", segment="nse_cm"),
    Instrument(symbol="DALBHARAT", token="8075", segment="nse_cm"),
    Instrument(symbol="DEEPAKNTR", token="19943", segment="nse_cm"),
    Instrument(symbol="DELTACORP", token="15044", segment="nse_cm"),
    Instrument(symbol="DIVISLAB", token="10940", segment="nse_cm"),
    Instrument(symbol="DIXON", token="21690", segment="nse_cm"),
    Instrument(symbol="DLF", token="14732", segment="nse_cm"),
    Instrument(symbol="DRREDDY", token="881", segment="nse_cm"),
    Instrument(symbol="EICHERMOT", token="910", segment="nse_cm"),
    Instrument(symbol="ESCORTS", token="958", segment="nse_cm"),
    Instrument(symbol="EXIDEIND", token="676", segment="nse_cm"),
    Instrument(symbol="FEDERALBNK", token="1023", segment="nse_cm"),
    Instrument(symbol="GAIL", token="4717", segment="nse_cm"),
    Instrument(symbol="GLENMARK", token="7406", segment="nse_cm"),
    Instrument(symbol="GMRAIRPORT", token="13528", segment="nse_cm"),
    Instrument(symbol="GNFC", token="1174", segment="nse_cm"),
    Instrument(symbol="GODREJCP", token="10099", segment="nse_cm"),
    Instrument(symbol="GODREJPROP", token="17875", segment="nse_cm"),
    Instrument(symbol="GRANULES", token="11872", segment="nse_cm"),
    Instrument(symbol="GRASIM", token="1232", segment="nse_cm"),
    Instrument(symbol="GSPL", token="13197", segment="nse_cm"),
    Instrument(symbol="GUJGASLTD", token="10599", segment="nse_cm"),
    Instrument(symbol="HAL", token="2303", segment="nse_cm"),
    Instrument(symbol="HAVELLS", token="9819", segment="nse_cm"),
    Instrument(symbol="HCLTECH", token="7229", segment="nse_cm"),
    Instrument(symbol="HDFCBANK", token="1333", segment="nse_cm"),
    Instrument(symbol="HDFCLIFE", token="467", segment="nse_cm"),
    Instrument(symbol="HEROMOTOCO", token="1348", segment="nse_cm"),
    Instrument(symbol="HINDALCO", token="1363", segment="nse_cm"),
    Instrument(symbol="HINDPETRO", token="1406", segment="nse_cm"),
    Instrument(symbol="HINDUNILVR", token="1394", segment="nse_cm"),
    Instrument(symbol="IBULLSLTD", token="24999", segment="nse_cm"),
    Instrument(symbol="ICICIBANK", token="4963", segment="nse_cm"),
    Instrument(symbol="IDFCFIRSTB", token="11184", segment="nse_cm"),
    Instrument(symbol="IEX", token="220", segment="nse_cm"),
    Instrument(symbol="IGL", token="11262", segment="nse_cm"),
    Instrument(symbol="INDHOTEL", token="1512", segment="nse_cm"),
    Instrument(symbol="INDIACEM", token="1515", segment="nse_cm"),
    Instrument(symbol="INDIGO", token="11195", segment="nse_cm"),
    Instrument(symbol="INDUSINDBK", token="5258", segment="nse_cm"),
    Instrument(symbol="INDUSTOWER", token="29135", segment="nse_cm"),
    Instrument(symbol="INFY", token="1594", segment="nse_cm"),
    Instrument(symbol="INTELLECT", token="5926", segment="nse_cm"),
    Instrument(symbol="IOC", token="1624", segment="nse_cm"),
    Instrument(symbol="IPCALAB", token="1633", segment="nse_cm"),
    Instrument(symbol="IRCTC", token="13611", segment="nse_cm"),
    Instrument(symbol="IRFC", token="2029", segment="nse_cm"),
    Instrument(symbol="ITC", token="1660", segment="nse_cm"),
    Instrument(symbol="JINDALSTEL", token="6733", segment="nse_cm"),
    Instrument(symbol="JIOFIN", token="18143", segment="nse_cm"),
    Instrument(symbol="JSWSTEEL", token="11723", segment="nse_cm"),
    Instrument(symbol="JUBLFOOD", token="18096", segment="nse_cm"),
    Instrument(symbol="KOTAKBANK", token="1922", segment="nse_cm"),
    Instrument(symbol="LALPATHLAB", token="11654", segment="nse_cm"),
    Instrument(symbol="LAURUSLABS", token="19234", segment="nse_cm"),
    Instrument(symbol="LICHSGFIN", token="1997", segment="nse_cm"),
    Instrument(symbol="LICI", token="9480", segment="nse_cm"),
    Instrument(symbol="LT", token="11483", segment="nse_cm"),
    Instrument(symbol="LTF", token="24948", segment="nse_cm"),
    Instrument(symbol="LTIM", token="17818", segment="nse_cm"),
    Instrument(symbol="LUPIN", token="10440", segment="nse_cm"),
    Instrument(symbol="M&M", token="2031", segment="nse_cm"),
    Instrument(symbol="MANAPPURAM", token="19061", segment="nse_cm"),
    Instrument(symbol="MARICO", token="4067", segment="nse_cm"),
    Instrument(symbol="MARUTI", token="10999", segment="nse_cm"),
    Instrument(symbol="MCX", token="31181", segment="nse_cm"),
    Instrument(symbol="METROPOLIS", token="9581", segment="nse_cm"),
    Instrument(symbol="MFSL", token="2142", segment="nse_cm"),
    Instrument(symbol="MGL", token="17534", segment="nse_cm"),
    Instrument(symbol="MOTHERSON", token="4204", segment="nse_cm"),
    Instrument(symbol="MPHASIS", token="4503", segment="nse_cm"),
    Instrument(symbol="MRF", token="2277", segment="nse_cm"),
    Instrument(symbol="MUTHOOTFIN", token="23650", segment="nse_cm"),
    Instrument(symbol="NAM-INDIA", token="357", segment="nse_cm"),
    Instrument(symbol="NATIONALUM", token="6364", segment="nse_cm"),
    Instrument(symbol="NAUKRI", token="13751", segment="nse_cm"),
    Instrument(symbol="NAVINFLUOR", token="14672", segment="nse_cm"),
    Instrument(symbol="NESTLEIND", token="17963", segment="nse_cm"),
    Instrument(symbol="NMDC", token="15332", segment="nse_cm"),
    Instrument(symbol="NTPC", token="11630", segment="nse_cm"),
    Instrument(symbol="OBEROIRLTY", token="20242", segment="nse_cm"),
    Instrument(symbol="OFSS", token="10738", segment="nse_cm"),
    Instrument(symbol="ONGC", token="2475", segment="nse_cm"),
    Instrument(symbol="PAGEIND", token="14413", segment="nse_cm"),
    Instrument(symbol="PERSISTENT", token="18365", segment="nse_cm"),
    Instrument(symbol="PETRONET", token="11351", segment="nse_cm"),
    Instrument(symbol="PFC", token="14299", segment="nse_cm"),
    Instrument(symbol="PIDILITIND", token="2664", segment="nse_cm"),
    Instrument(symbol="PIIND", token="24184", segment="nse_cm"),
    Instrument(symbol="PIRAMALFIN", token="759551", segment="nse_cm"),
    Instrument(symbol="PNB", token="10666", segment="nse_cm"),
    Instrument(symbol="POLYCAB", token="9590", segment="nse_cm"),
    Instrument(symbol="POWERGRID", token="14977", segment="nse_cm"),
    Instrument(symbol="PVRINOX", token="13147", segment="nse_cm"),
    Instrument(symbol="RAMCOCEM", token="2043", segment="nse_cm"),
    Instrument(symbol="RBLBANK", token="18391", segment="nse_cm"),
    Instrument(symbol="RECLTD", token="15355", segment="nse_cm"),
    Instrument(symbol="RELIANCE", token="2885", segment="nse_cm"),
    Instrument(symbol="SAIL", token="2963", segment="nse_cm"),
    Instrument(symbol="SBILIFE", token="21808", segment="nse_cm"),
    Instrument(symbol="SBIN", token="3045", segment="nse_cm"),
    Instrument(symbol="SHREECEM", token="3103", segment="nse_cm"),
    Instrument(symbol="SHRIRAMFIN", token="4306", segment="nse_cm"),
    Instrument(symbol="SIEMENS", token="3150", segment="nse_cm"),
    Instrument(symbol="SRF", token="3273", segment="nse_cm"),
    Instrument(symbol="STAR", token="7374", segment="nse_cm"),
    Instrument(symbol="SUNPHARMA", token="3351", segment="nse_cm"),
    Instrument(symbol="SUNTV", token="13404", segment="nse_cm"),
    Instrument(symbol="SYNGENE", token="10243", segment="nse_cm"),
    Instrument(symbol="TATACOMM", token="3721", segment="nse_cm"),
    Instrument(symbol="TATACONSUM", token="3432", segment="nse_cm"),
    Instrument(symbol="TATAELXSI", token="3411", segment="nse_cm"),
    Instrument(symbol="TATAPOWER", token="3426", segment="nse_cm"),
    Instrument(symbol="TATASTEEL", token="3499", segment="nse_cm"),
    Instrument(symbol="TCS", token="11536", segment="nse_cm"),
    Instrument(symbol="TECHM", token="13538", segment="nse_cm"),
    Instrument(symbol="TITAN", token="3506", segment="nse_cm"),
    Instrument(symbol="TMPV", token="3456", segment="nse_cm"),
    Instrument(symbol="TORNTPHARM", token="3518", segment="nse_cm"),
    Instrument(symbol="TORNTPOWER", token="13786", segment="nse_cm"),
    Instrument(symbol="TRENT", token="1964", segment="nse_cm"),
    Instrument(symbol="TVSMOTOR", token="8479", segment="nse_cm"),
    Instrument(symbol="ULTRACEMCO", token="11532", segment="nse_cm"),
    Instrument(symbol="UNIONBANK", token="10753", segment="nse_cm"),
    Instrument(symbol="UNITDSPR", token="10447", segment="nse_cm"),
    Instrument(symbol="UPL", token="11287", segment="nse_cm"),
    Instrument(symbol="VEDL", token="3063", segment="nse_cm"),
    Instrument(symbol="VOLTAS", token="3718", segment="nse_cm"),
    Instrument(symbol="WHIRLPOOL", token="18011", segment="nse_cm"),
    Instrument(symbol="WIPRO", token="3787", segment="nse_cm"),
    Instrument(symbol="ZEEL", token="3812", segment="nse_cm"),
    Instrument(symbol="ZYDUSLIFE", token="7929", segment="nse_cm"),
]


# Lookup helpers
INSTRUMENT_BY_SYMBOL = {inst.symbol: inst for inst in INSTRUMENTS}
INSTRUMENT_BY_TOKEN = {inst.token: inst for inst in INSTRUMENTS}


def get_all_symbols() -> list[str]:
    """Return list of all ticker symbols."""
    return [inst.symbol for inst in INSTRUMENTS]


def get_instrument_count() -> int:
    """Return total number of registered instruments."""
    return len(INSTRUMENTS)
